export const REQUEST_POKEMON_LOADING = 'REQUEST_POKEMON_LOADING'
export const REQUEST_POKEMON_SUCCESS = 'REQUEST_POKEMON_SUCCESS'
export const REQUEST_POKEMON_FAILURE = 'REQUEST_POKEMON_FAILURE'

export const ADD_POKEMON_LIST = 'ADD_POKEMON_LIST'
export const ADD_POKEMONS = 'ADD_POKEMONS'
export const ADD_CURRENT_POKEMON = 'ADD_CURRENT_POKEMON'
export const ADD_POKEMON_ITEM = 'ADD_POKEMON_ITEM'

export const REQUEST_POKEMON_ITEM_LOADING = 'REQUEST_POKEMON_ITEM_LOADING'
export const REQUEST_POKEMON_ITEM_SUCCESS = 'REQUEST_POKEMON_ITEM_SUCCESS'
export const REQUEST_POKEMON_ITEM_FAILURE = 'REQUEST_POKEMON_ITEM_FAILURE'


